name:                projectEuler
version:             0.1.0.0
github:              "githubuser/projectEuler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/projectEuler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  # q1:
  #   main:                Main.hs
  #   source-dirs:         app/q1
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q2:
  #   main:                Main.hs
  #   source-dirs:         app/q2
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q3:
  #   main:                Main.hs
  #   source-dirs:         app/q3
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q4:
  #   main:                Main.hs
  #   source-dirs:         app/q4
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q5:
  #   main:                Main.hs
  #   source-dirs:         app/q5
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q6:
  #   main:                Main.hs
  #   source-dirs:         app/q6
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q7:
  #   main:                Main.hs
  #   source-dirs:         app/q7
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q8:
  #   main:                Main.hs
  #   source-dirs:         app/q8
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q9:
  #   main:                Main.hs
  #   source-dirs:         app/q9
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q10:
  #   main:                Main.hs
  #   source-dirs:         app/q10
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q11:
  #   main:                Main.hs
  #   source-dirs:         app/q11
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler
  #   - vector

  # q12:
  #   main:                Main.hs
  #   source-dirs:         app/q12
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q13:
  #   main:                Main.hs
  #   source-dirs:         app/q13
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q14:
  #   main:                Main.hs
  #   source-dirs:         app/q14
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q15:
  #   main:                Main.hs
  #   source-dirs:         app/q15
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q16:
  #   main:                Main.hs
  #   source-dirs:         app/q16
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  q17:
    main:                Main.hs
    source-dirs:         app/q17
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projectEuler
    - unordered-containers

tests:
  projectEuler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projectEuler
