name:                projectEuler
version:             0.1.0.0
github:              "githubuser/projectEuler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/projectEuler#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- unordered-containers
- containers
- split

library:
  source-dirs: src

executables:
  # q1:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q1
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q2:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q2
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q3:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q3
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q4:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q4
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q5:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q5
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q6:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q6
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q7:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q7
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q8:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q8
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q9:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q9
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q10:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q10
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q11:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q11
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q12:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q12
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q13:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q13
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q14:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q14
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q15:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q15
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q16:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q16
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q17:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q17
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q18:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q18
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q19:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q19
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q20:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q20
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q21:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q21
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q22:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q22
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q23:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q23
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q24:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q24
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q25:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q25
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q26:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q26
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q27:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q27
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q28:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q28
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q29:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q29
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q30:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q30
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q31:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q31
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q32:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q32
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q33:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q33
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q34:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q34
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q35:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q35
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q36:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q36
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q37:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q37
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q38:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q38
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q39:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q39
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q40:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q40
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q41:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q41
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q42:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q42
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q43:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q43
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q44:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q44
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q45:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q45
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q46:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q46
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q47:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q47
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q48:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q48
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q49:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q49
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q50:
  #   main:                Main.hs
  #   source-dirs:         app/p1/q50
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q51:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q51
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q52:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q52
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q53:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q53
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q54:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q54
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q55:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q55
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q56:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q56
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q57:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q57
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q58:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q58
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q59:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q59
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q60:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q60
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q61:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q61
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  q62:
    main:                Main.hs
    source-dirs:         app/p2/q62
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projectEuler

  # q67:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q67
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler

  # q68:
  #   main:                Main.hs
  #   source-dirs:         app/p2/q68
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - projectEuler


tests:
  projectEuler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projectEuler
